document.addEventListener('DOMContentLoaded', function() {
// Dimensions of the map container
const mapWidth = 600;
const mapHeight = 400;

// Define the map of known artists and their genres
const artistGenreMap = {
  "Elvis Costello": "PUNK ROCK",
  "Elvis Costello & The Attractions": "PUNK ROCK",
  "Tiffany Page": "Alternative",
  "Joe Echo": "ROCK",
  "Paul McCartney": "BRITISH/ROCK",
  "Lissie": "ROCK",
  "The All-American Rejects": "INDIE/ALTERNATIVE",
  "Demi Lovato": "POP",
  "Babyshambles": "INDIE/ALTERNATIVE",
  "Lilygreen & Maguire": "POP",
  "Taylor Swift": "POP",
  "Amanda Seyfried": "SOUNDTRACK",
  "Olly Murs": "POP",
  "The Pigeon Detectives": "INDIE/ALTERNATIVE",
  "James Blunt": "POP/INDIE",
  "Luther Vandross": "R&B",
  "Glee Cast": "SOUNDTRACK",
  "Anna Kendrick": "SOUNDTRACK",
  "Daniel Powter": "POP/ALTERNATIVE",
  "Snow Patrol": "INDIE/ALTERNATIVE",
  "OneRepublic": "ROCK",
  "Allstar Weekend": "POP",
  "Ed Sheeran": "ACOUSTIC",
  "Coldplay": "ROCK/ALTERNATIVE",
  "The 1975": "INDIE/ROCK",
  "Butterfly Boucher": "INDIE/ALTERNATIVE",
  "Christina Aguilera": "POP",
  "Beans On Toast": "FOLK",
  "Cast Of 'Camp Rock 2": "SOUNDTRACK",
  "Elton John": "POP",
  "Lennon & Maisy": "COUNTRY",
  "Beyoncé": "POP",
  "One Direction": "POP",
  "Frank Turner": "FOLK",
  "S Club 7": "POP",
  "Hugh Jackman": "SOUNDTRACK",
  "Kelly Clarkson": "POP",
  "Simon & Garfunkel": "FOLK",
  "Eliza Doolittle": "POP",
  "Barenaked Ladies": "ROCK/ALTERNATIVE",
  "Boyzone": "POP",
  "Young Money": "RAP",
  "Rachael Yamagata": "INDIE/ALTERNATIVE",
  "The Twang": "INDIE",
  "Frank Turner": "FOLK",
  "Justin Bieber": "POP",
  "Lily Allen": "POP",
  "Cat Stevens": "FOLK",
  "The Pogues": "IRISH",
  "Bob Carlisle": "CHRISTIAN",
  "Newton Faulkner": "FOLK",
  "Passenger": "FOLK",
  "Mat Kearney": "ACOUSTIC",
  "Oasis": "BRITISH/ROCK",
  "A Great Big World": "INDIE/ALTERNATIVE",
  "Matt Nathanson": "ACOUSTIC",
  "Ryan O'Shaughnessy": "IRISH/ACOUSTIC",
  "The Rifles": "INDIE/ALTERNATIVE",
  "KISS": "ROCK",
  "Red Hot Chili Peppers": "ROCK/ALTERNATIVE",
  "Michael Jackson": "POP",
  "Daft Punk": "ELECTRONIC",
  "Danny Elfman": "SOUNDTRACK",
  "Joe Hisaishi": "JAPANESE/SOUNDTRACK",
  "KIRAKIRA Quartet": "JAPANESE/SOUNDTRACK",
  "Moby": "ELECTRONIC",
  "Ratatat": "ELECTRONIC",
  "All That Jazz": "JAZZ/JAPANESE",
  "Pendulum": "ELECTRONIC",
  "Justice": "ELECTRONIC/FRENCH",
  "Wolfgang Amadeus Mozart": "CLASSICAL",
  "Antonio Vivaldi": "CLASSICAL",
  "Ludwig van Beethoven": "CLASSICAL",
  "Drake": "RAP/HIP-HOP",
  "2080": "ELECTRONIC/FRENCH",
  "C418": "ELECTRONIC",
  "Glen Porter": "HIP-HOP/LOUNGE",
  "Bonobo": "ELECTRONIC/LOUNGE",
  "Schoolboy Q": "RAP/HIP-HOP",
  "Athletics": "INDIE/ALTERNATIVE",
  "Black Sabbath": "METAL",
  "Led Zeppelin": "ROCK",
  "Arctic Monkeys": "BRITISH/INDIE",
  "London Grammar": "INDIE/ELECTRONIC",
  "Otis Redding": "R&B",
  "Johnny Cash": "COUNTRY"
  // Add more artists and their genres as needed
};

let rowConverter = function (d) {
  return {
    id: d.user_id,
    artistName: d.artistname,
    trackName: d.trackname,
    playlistName: d.playlistname
  };
}

});